### PR TITLE
fix: fix missing pip bug and add 'python_executable' option

### PR DESCRIPTION
**Pull request by rickstaa**
This pull request makes sure that pip will be installed when it is not found. It also adds the `python_executable` action argument, allowing users to specify the python executable they want to use. It was created to solve #35.

### CODE REVIEW

**Review by tsuyoshicho — COMMENTED** [review]
I think that there is basically no problem.
Also, I don't think there is a problem with making Python specifiable.
(It may be better to make pip also specifiable)

However, there are the following problems.
* Is it okay to change the execution environment for subsequent workflows by installing pip? (Assuming that flake8 has no problem)
* If it is a local runner, isn't it the creator's responsibility to create an environment where actions can be executed? (Python symlink, install pip)
(Note: Python setup itself in a normal GHA environment is the responsibility of `actions/setup-python`)

There is a question as to whether it can be corrected as it is.

**Comment by tsuyoshicho** [comment]
ping @rickstaa san

**Comment by rickstaa** [comment]
@tsuyoshicho Thanks a lot for your feedback!

> Is it okay to change the execution environment for subsequent workflows by installing pip? (Assuming that flake8 has no problem).

That's an excellent point. On second thought, I don't think most people would appreciate this. Especially since I'm using the non recommended way of installing pip to support more distributions. Maybe, throw a warning when pip is not found? Alternatively, can we create an `install_pip` action argument and set the default to `false`?

> If it is a local runner, isn't it the creator's responsibility to create an environment where actions can be executed? (Python symlink, install pip)
(Note: Python setup itself in a normal GHA environment is the responsibility of actions/setup-python)

Again I think you are right on this point. Maybe let's throw a warning when python is not found?

Let me know what you think so that I can change this pull request.

**Comment by tsuyoshicho** [comment]
@rickstaa Thanks response.

I think fix these two point.

* `python`  is configurable (to include python3 or specific version `/bin/python3.10`)
* `limitation: action-flake8` user to required either:
  - flake8 setup was already done
  - python with pip setup was already

**Comment by tsuyoshicho** [comment]
re-ping @rickstaa san

**Comment by rickstaa** [comment]
@tsuyoshicho, due to my thesis, sadly haven't had the time to update this PR. You can, of course, also change the pull request yourself to the form you see fit and ask me to review it. Or we can just close it since, as you pointed out in https://github.com/reviewdog/action-flake8/pull/36#pullrequestreview-914991630 the problem encountered in https://github.com/reviewdog/action-flake8/issues/35 is quite an edge use case that will likely not be encountered by a lot of people. 🤔

**Review by tsuyoshicho — APPROVED** [review]
Alright, I think it doesn't matter which one you choose.
I will approve this PR.

**Pull request closed without merging**
